### ISSUE TITLE
a mistake maybe

### ISSUE THREAD

**Issue by hinyb** [barrybingo/CNaturalMouseMotion#1]
in the DefaultProvider.h , line 248 return {pt.y, pt.y};
I think it should be return {pt.x, pt.y};
I am a beginer in c++ , please forgive my ignorance.

**Comment by barrybingo** [comment]
Good catch.
Issue a pull request and I'm merge it.

**Comment by hinyb** [comment]
Thank for your praise,you are always so enthusiastic。
But I dont know how to pull request , I am try to use github recently.
I am sorry for my ignorance.

**Comment by barrybingo** [comment]
Take your time, no rush for the PR.
This can be a practice :)

**Comment by barrybingo** [comment]
Thanks for the bug fix

**Comment by hinyb** [comment]
Thank for your encouragement.You are always good at encouraging others : )
